import React from "react";


const comunasList = [
    { value: "Alhué", label: "Alhué" },
    { value: "Buin", label: "Buin" },
    { value: "Calera de Tango", label: "Calera de Tango" },
    { value: "Cerrillos", label: "Cerrillos" },
    { value: "Cerro Navia", label: "Cerro Navia" },
    { value: "Colina", label: "Colina" },
    { value: "Conchalí", label: "Conchalí" },
    { value: "Curacaví", label: "Curacaví" },
    { value: "El Bosque", label: "El Bosque" },
    { value: "El Monte", label: "El Monte" },
    { value: "Estación Central", label: "Estación Central" },
    { value: "Huechuraba", label: "Huechuraba" },
    { value: "Independencia", label: "Independencia" },
    { value: "Isla de Maipo", label: "Isla de Maipo" },
    { value: "La Cisterna", label: "La Cisterna" },
    { value: "La Florida", label: "La Florida" },
    { value: "La Granja", label: "La Granja" },
    { value: "La Pintana", label: "La Pintana" },
    { value: "La Reina", label: "La Reina" },
    { value: "Lampa", label: "Lampa" },
    { value: "Las Condes", label: "Las Condes" },
    { value: "Lo Barnechea", label: "Lo Barnechea" },
    { value: "Lo Espejo", label: "Lo Espejo" },
    { value: "Lo Prado", label: "Lo Prado" },
    { value: "Macul", label: "Macul" },
    { value: "Maipú", label: "Maipú" },
    { value: "María Pinto", label: "María Pinto" },
    { value: "Melipilla", label: "Melipilla" },
    { value: "Ñuñoa", label: "Ñuñoa" },
    { value: "Padre Hurtado", label: "Padre Hurtado" },
    { value: "Paine", label: "Paine" },
    { value: "Pedro Aguirre Cerda", label: "Pedro Aguirre Cerda" },
    { value: "Peñaflor", label: "Peñaflor" },
    { value: "Peñalolén", label: "Peñalolén" },
    { value: "Pirque", label: "Pirque" },
    { value: "Providencia", label: "Providencia" },
    { value: "Pudahuel", label: "Pudahuel" },
    { value: "Puente Alto", label: "Puente Alto" },
    { value: "Quilicura", label: "Quilicura" },
    { value: "Quinta Normal", label: "Quinta Normal" },
    { value: "Recoleta", label: "Recoleta" },
    { value: "Renca", label: "Renca" },
    { value: "San Bernardo", label: "San Bernardo" },
    { value: "San Joaquín", label: "San Joaquín" },
    { value: "San José de Maipo", label: "San José de Maipo" },
    { value: "San Miguel", label: "San Miguel" },
    { value: "San Pedro", label: "San Pedro" },
    { value: "San Ramón", label: "San Ramón" },
    { value: "Santiago", label: "Santiago" },
    { value: "Talagante", label: "Talagante" },
    { value: "Tiltil", label: "Tiltil" },
    { value: "Vitacura", label: "Vitacura" },
  ];

  export default comunasList;